AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Tutorial
Parameters:
  Environment:
    Type: String
Resources:
  PagesLamdba:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub PagesLambda-${Environment}
      Handler: lambdahandler.gatewaylambda
      Runtime: nodejs6.10 
      MemorySize: 128 
      Timeout: 30
      CodeUri: .
      Environment:
                Variables:
                    Environment: !Ref Environment
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        MyEndpoint:
          Type: Api 
          Properties:
            Path: /v4/pages
            Method: get
