AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Tutorial
Parameters:
  Environment:
    Type: String
Resources:
  # PagesAPI:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: !Sub ${Environment}
  #     DefinitionBody:
  #       swagger: 2.0
  #       info:
  #         title:
  #           Ref: AWS::StackName
  #       x-amazon-apigateway-binary-media-types:
  #         - '*/*'
  #       paths:
  #         /v3/pages:
  #           get:
  #             x-amazon-apigateway-integration:
  #               httpMethod: GET
  #               uri:
  #                 !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PagesLamdba.Arn}/invocations
  #             responses: {}
  PagesLamdba:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub PagesLambda-${Environment}
      Handler: lambdahandler.gatewaylambda
      Runtime: nodejs6.10 
      MemorySize: 128 
      Timeout: 30
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        MyEndpoint:
          Type: Api 
          Properties:
            Path: /v4/pages
            Method: get  
